/* CREATE TABLE */
CREATE TABLE BANKS(
Code DOUBLE,
name VARCHAR(100),
short_name VARCHAR(100)
);

/* INSERT QUERY NO: 1 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
34, 'BANCO PATAGONIA', 'PATAGONIA'
);

/* INSERT QUERY NO: 2 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
285, 'BANCO MACRO', 'MACRO'
);

/* INSERT QUERY NO: 3 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
14, 'BANCO DE LA PROVINCIA DE BS.AS.', 'BAPRO'
);

/* INSERT QUERY NO: 4 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
15, 'ICBC', 'ICBC'
);

/* INSERT QUERY NO: 5 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
150, 'HSBC BANK ARGENTINA', 'HSBC'
);

/* INSERT QUERY NO: 6 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
16, 'SANTANDER RIO (ex C-Bank)', 'SANTANDER ex C-Bank'
);

/* INSERT QUERY NO: 7 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
17, 'BBVA', 'BBVA'
);

/* INSERT QUERY NO: 8 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
191, 'BANCO CREDICOOP', 'CREDICOOP'
);

/* INSERT QUERY NO: 9 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
259, 'BANCO ITAU ARGENTINA', 'ITAU'
);

/* INSERT QUERY NO: 10 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
27, 'BANCO SUPERVIELLE', 'SUPERVIELLE'
);

/* INSERT QUERY NO: 11 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
29, 'BANCO CIUDAD DE BUENOS AIRES', 'CIUDAD'
);

/* INSERT QUERY NO: 12 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
299, 'BANCO COMAFI', 'COMAFI'
);

/* INSERT QUERY NO: 13 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
330, 'NUEVO BANCO DE SANTA FE', 'NBSF'
);

/* INSERT QUERY NO: 14 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
44, 'BANCO HIPOTECARIO', 'HIPOTECARIO'
);

/* INSERT QUERY NO: 15 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
11, 'BANCO DE LA NACION ARGENTINA', 'NACION'
);

/* INSERT QUERY NO: 16 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
60, 'BANCO DEL TUCUMAN', 'TUCUMAN'
);

/* INSERT QUERY NO: 17 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
7, 'BANCO GALICIA', 'GALICIA'
);

/* INSERT QUERY NO: 18 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
72, 'SANTANDER RIO', 'SANTANDER RIO'
);

/* INSERT QUERY NO: 19 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
999, 'OTROS', 'OTROS'
);

/* INSERT QUERY NO: 20 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
45, 'BANCO DE SAN JUAN', 'SAN JUAN'
);

/* INSERT QUERY NO: 21 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
86, 'BANCO SANTA CRUZ', 'SANTA CRUZ'
);

/* INSERT QUERY NO: 22 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
322, 'BIND', 'BIND'
);

/* INSERT QUERY NO: 23 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
386, 'NUEVO BANCO DE ENTRE RIOS', 'BERSA'
);

/* INSERT QUERY NO: 24 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
389, 'COLUMBIA', 'COLUMBIA'
);

/* INSERT QUERY NO: 25 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
450, 'TARJETA NARANJA', 'NARANJA'
);

/* INSERT QUERY NO: 26 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
455, 'NEVADA', 'NEVADA'
);

/* INSERT QUERY NO: 27 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
499, 'MIRA', 'MIRA'
);

/* INSERT QUERY NO: 28 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
515, 'TARSHOP', 'TARSHOP'
);

/* INSERT QUERY NO: 29 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
77, 'EFECTIVO SI', 'EFECTIVO SI'
);

/* INSERT QUERY NO: 30 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
800, 'AMEX', 'AMEX'
);

/* INSERT QUERY NO: 31 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
801, 'NARANJA', 'NARANJA'
);

/* INSERT QUERY NO: 32 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
148, 'BANCO MUNICIPAL DE LA PLATA', 'LA PLATA'
);

/* INSERT QUERY NO: 33 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
20, 'BANCO DE CORDOBA', 'CORDOBA'
);

/* INSERT QUERY NO: 34 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
65, 'BANCO MUNICIPAL DE ROSARIO', 'ROSARIO'
);

/* INSERT QUERY NO: 35 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
66, 'CONSUMAX', 'ROSARIO/CON'
);

/* INSERT QUERY NO: 36 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
83, 'BANCO DEL CHUBUT', 'CHUBUT'
);

/* INSERT QUERY NO: 37 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
93, 'BANCO DE LA PAMPA', 'PAMPA'
);

/* INSERT QUERY NO: 38 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
94, 'BANCO DE CORRIENTES', 'CORRIENTES'
);

/* INSERT QUERY NO: 39 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
97, 'BANCO PROVINCIA DE NEUQUEN', 'NEUQUEN'
);

/* INSERT QUERY NO: 40 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
121, 'PROVENCRED', 'PROVENCRED'
);

/* INSERT QUERY NO: 41 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
268, 'BANCO DE TIERRA DEL FUEGO', 'TIERRA FUEGO'
);

/* INSERT QUERY NO: 42 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
277, 'BANCO SAENZ', 'SAENZ'
);

/* INSERT QUERY NO: 43 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
301, 'BANCO PIANO', 'PIANO'
);

/* INSERT QUERY NO: 44 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
303, 'BANCO FINANSUR', 'FINANSUR'
);

/* INSERT QUERY NO: 45 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
309, 'NUEVO BANCO DE LA RIOJA', 'LA RIOJA'
);

/* INSERT QUERY NO: 46 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
311, 'NUEVO BANCO DEL CHACO', 'CHACO'
);

/* INSERT QUERY NO: 47 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
315, 'BANCO DE FORMOSA', 'FORMOSA'
);

/* INSERT QUERY NO: 48 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
321, 'BANCO DE SANTIAGO DEL ESTERO', 'SANTIAGO'
);

/* INSERT QUERY NO: 49 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
331, 'BANCO CETELEM', 'CETELEM'
);

/* INSERT QUERY NO: 50 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
341, 'BANCO MAS VENTAS', 'MAS VENTAS'
);

/* INSERT QUERY NO: 51 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
416, 'NATIVA NACION', 'NATIVA'
);

/* INSERT QUERY NO: 52 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
426, 'BANCO BICA', 'BICA'
);

/* INSERT QUERY NO: 53 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
431, 'BANCO COINAG', 'COINAG'
);

/* INSERT QUERY NO: 54 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
468, 'BANCO FUEGUINA', 'FUEGUINA'
);

/* INSERT QUERY NO: 55 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
488, 'BANCO CAJA POPULAR DE TUCUMAN', 'TUCUMAN'
);

/* INSERT QUERY NO: 56 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
310, 'BANCO DEL SOL', 'DEL SOL'
);

/* INSERT QUERY NO: 57 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
338, 'BST', 'BST'
);

/* INSERT QUERY NO: 58 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
269, 'BANCO DE LA REP. ORIENTAL DEL URUGUAY', 'URUGUAY'
);

/* INSERT QUERY NO: 59 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
247, 'BANCO ROELA SA', 'ROELA'
);

/* INSERT QUERY NO: 60 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
281, 'BANCO MERIDIAN SA', 'MERIDIAN'
);

/* INSERT QUERY NO: 61 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
448, 'FINANDINO', 'FINANDINO'
);

/* INSERT QUERY NO: 62 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
316, 'CITIBANK', 'CITI'
);

/* INSERT QUERY NO: 63 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
802, 'CREDIMAS', 'CREDIMAS'
);

/* INSERT QUERY NO: 64 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
143, 'Brubank', 'Brubank'
);

/* INSERT QUERY NO: 65 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
384, 'Wilobank', 'Wilobank'
);

/* INSERT QUERY NO: 66 */
INSERT INTO BANKS(Code, name, short_name)
VALUES
(
415, 'Rebanking', 'Rebanking'
);
